# Generated by Django 2.0.2 on 2020-05-31 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('acc_no', models.CharField(default='', max_length=10, verbose_name='Account Number')),
                ('bank_name', models.CharField(choices=[('Allahabad Bank', 'Allahabad Bank'), ('Andhra Bank', 'Andhra Bank'), ('Axis Bank', 'Axis Bank'), ('Bank of Bahrain and Kuwait', 'Bank of Bahrain and Kuwait'), ('Bank of Baroda - Corporate Banking', 'Bank of Baroda - Corporate Banking'), ('Bank of Baroda - Retail Banking', 'Bank of Baroda - Retail Banking'), ('Bank of India', 'Bank of India'), ('Bank of Maharashtra', 'Bank of Maharashtra'), ('Canara Bank', 'Canara Bank'), ('Central Bank of India', 'Central Bank of India'), ('City Union Bank', 'City Union Bank'), ('Corporation Bank', 'Corporation Bank'), ('Deutsche Bank', 'Deutsche Bank'), ('Development Credit Bank', 'Development Credit Bank'), ('Dhanlaxmi Bank', 'Dhanlaxmi Bank'), ('Federal Bank', 'Federal Bank'), ('ICICI Bank', 'ICICI Bank'), ('IDBI Bank', 'IDBI Bank'), ('Indian Bank', 'Indian Bank'), ('Indian Overseas Bank', 'Indian Overseas Bank'), ('IndusInd Bank', 'IndusInd Bank'), ('ING Vysya Bank', 'ING Vysya Bank'), ('Jammu and Kashmir Bank', 'Jammu and Kashmir Bank'), ('Karnataka Bank Ltd', 'Karnataka Bank Ltd'), ('Karur Vysya Bank', 'Karur Vysya Bank'), ('Kotak Bank', 'Kotak Bank'), ('Laxmi Vilas Bank', 'Laxmi Vilas Bank'), ('Oriental Bank of Commerce', 'Oriental Bank of Commerce'), ('Punjab National Bank - Corporate Banking', 'Punjab National Bank - Corporate Banking'), ('Punjab National Bank - Retail Banking', 'Punjab National Bank - Retail Banking'), ('Punjab & Sind Bank', 'Punjab & Sind Bank'), ('Shamrao Vitthal Co-operative Bank', 'Shamrao Vitthal Co-operative Bank'), ('South Indian Bank', 'South Indian Bank'), ('State Bank of Bikaner & Jaipur', 'State Bank of Bikaner & Jaipur'), ('State Bank of Hyderabad', 'State Bank of Hyderabad'), ('State Bank of India', 'State Bank of India'), ('State Bank of Mysore', 'State Bank of Mysore'), ('State Bank of Patiala', 'State Bank of Patiala'), ('State Bank of Travancore', 'State Bank of Travancore'), ('Syndicate Bank', 'Syndicate Bank'), ('Tamilnad Mercantile Bank Ltd.', 'Tamilnad Mercantile Bank Ltd.'), ('UCO Bank', 'UCO Bank'), ('Union Bank of India', 'Union Bank of India'), ('United Bank of India', 'United Bank of India'), ('Vijaya Bank', 'Vijaya Bank'), ('Yes Bank Ltd', 'Yes Bank Ltd')], default='', max_length=50, verbose_name='Bank Name')),
                ('acc_hol_name', models.CharField(default='', max_length=30, verbose_name='Account Holder Name')),
                ('ifsc', models.CharField(default='', max_length=10, verbose_name='IFSC')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('trasaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('trasaction_date', models.DateField(auto_now=True)),
                ('borrow_amt', models.IntegerField(blank=True, choices=[(500, '500'), (1000, '1000'), (1500, '1500')])),
                ('borrow_month', models.IntegerField(blank=True, choices=[(1, '1 Month'), (2, '2 Months'), (3, '3 Months')])),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('aadharCardNo', models.CharField(max_length=12, verbose_name='Aadhar Card No')),
                ('panCardNo', models.CharField(max_length=10, verbose_name='Pan Card No')),
                ('frontPan', models.FileField(default='', upload_to='studentloan/images', verbose_name='Front Pan')),
                ('backPan', models.FileField(default='', upload_to='studentloan/images', verbose_name='Back Pan')),
                ('frontAadhar', models.FileField(default='', upload_to='studentloan/images/', verbose_name='Front Aadhar')),
                ('backAadhar', models.FileField(default='', upload_to='studentloan/images/', verbose_name='Back Aadhar')),
                ('selfie', models.FileField(blank=True, null=True, upload_to='studentloan/images/', verbose_name='Selfie')),
                ('fine', models.IntegerField(blank=True, default=0, verbose_name='Fine')),
                ('completion', models.CharField(blank=True, default='partial', max_length=10, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Lend',
            fields=[
                ('trasaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('trasaction_date', models.DateField(auto_now=True)),
                ('lend_amt', models.IntegerField(blank=True, choices=[(500, '500'), (1000, '1000'), (1500, '1500')])),
                ('lend_month', models.IntegerField(blank=True, choices=[(1, '1 Month'), (2, '2 Months'), (3, '3 Months')])),
                ('username', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='studentloan.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='borrow',
            name='username',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bank',
            name='username',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
