# Generated by Django 2.0.2 on 2020-05-31 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentloan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='username',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='studentloan.Customer'),
        ),
    ]
