# Generated by Django 2.0.2 on 2020-05-31 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentloan', '0002_auto_20200531_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='username',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
